import type {NextPage} from 'next'
import Head from 'next/head'
import Link from "next/link";
import {useEffect} from "react";
import {useRouter} from "next/router";

const Home: NextPage = () => {

    const router = useRouter();

    useEffect(() => {
        const data = false;
        if (data) {
            console.log("redirect");
            router.push('/login');
        }
    }, []);

    return (<div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>

        <Link href="/login/index">
            <div>lcick!!</div>
        </Link>


    </div>)
}

export default Home
